baseurl = "/"
title = "estebanvalencia.com"
theme = "hugo-theme-console"
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true
  footerText = "*“The soul that is within me no man can degrade.”* – Frederick Douglass"

  [[params.navlinks]]
  name = "me/"
  url = "me/"

  [[params.navlinks]]
  name = "collection/"
  url = "collection/"
  
  [[params.navlinks]]
  name = "photos/"
  url = "photos/"
  
[[params.plugins.css]]
URL = "css/hugo-easy-gallery.css"
[[params.plugins.css]]
URL = "css/style.css"
