baseurl = "https://estebanvalencia.com/"
title = "estebanvalencia.com"
googleAnalytics = "G-T1S5YBNW8N"

theme = ["ev-console"]
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "index\\.html", "about\\.html", "static/blog/\\*_files/", "README","\\.knit\\.md$", "\\.utf8\\.md$"] 
ignoreErrors = ["error-remote-getjson"]
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
languageCode = "en-us"
[markup.goldmark.renderer]
unsafe = true

[author]
  name= "Esteban Valencia"
  image= "me/tux.webm"
  about= "Esteban Valencia, Product Creator, is building better suites of products to deliver on company's business goals."
  email= "me@estebanvalencia.com"
  domain= "https://estebanvalencia.com"



[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true
  pre = "Esteban | ˈe-stə-vən" 
  footerText ="*“The three great essentials to achieve anything worth while are: Hard work, Stick-to-itiveness, and Common sense.”* - Thomas A. Edison"
  buildText ="Last Build: Friday June 16, 2023 at 10:46 PM (Eastern Time)"
  summaryImg = "/me/tux.webm"
  summary = "**Hi visitor!  If you're not quite sure where to start, here's a a heart warming summary about myself and the joys of reading my content.  TL;DR - This page is dedicated to the things I enjoy like data, development, music, books and plenty of other things!**"
  description = "Bite-sized ideas sourced from the internet"
  images = ["/favicon/apple-touch-icon-57x57.png"]
  favicon = "sam.ico"
  amp = true
  ampElements = ["amp-accordion","amp-ad","amp-analytics","amp-app-banner","amp-carousel","amp-iframe","amp-dynamic-css-classes","amp-form","amp-fx-flying-carpet","amp-image-lightbox","amp-lightbox","amp-sidebar","amp-social-share","amp-sticky-ad","amp-user-notification"]
  themeColor = "#ff1d55"
  adsensePublisher = "ca-pub-123456789"
  appleItunesApp = "app-id=123456789, app-argument=app-name://link/to/app-content"
  ampManifest = "/amp-manifest.json"
  alternatePageName = "HUGO AMP"
  organizationLogo = "https://gohugo-amp.gohugohq.com/logo.png"
  organizationName = "gohugohq.com"
  organizationAddress = "Some Street 123, 12345 City"
  socialProfiles = ["http://www.facebook.com/your-profile","http://instagram.com/yourProfile","http://www.linkedin.com/in/yourprofile","http://plus.google.com/your_profile"]
  publisherName = "gohugohq.com"
  publisherLogo = "https://gohugo-amp.gohugohq.com/logo-publisher.png" # https://developers.google.com/search/docs/data-types/articles#logo-guidelines
  publisherLogoWidth = 600
  publisherLogoHeight = 60
  stylesheetRegular = ["/base-styling.css"] # these styles are used when amp is disabled for a specific page
  javascriptRegular = ["/script.js"] # these scripts are used when amp is disabled for a specific page

  
[[params.navlinks]]
name = "me/"
url = "me/"

[[params.navlinks]]
name = "books/"
url = "books/"

[[params.navlinks]]
name = "collection/"
url = "collection/"
  
[[params.navlinks]]
name = "photos/"
url = "photos/"
  
[[params.plugins.css]]
URL = "ev-console/css/terminal-0.7.1.min.css"
[[params.plugins.css]]
URL = "ev-console/css/animate-3.7.2.min.css"
[[params.plugins.css]]
URL = "ev-console/css/console.css"
[[params.plugins.css]]
URL = "css/hugo-easy-gallery.css"
[[params.plugins.css]]
URL = "css/style.css"


[params.twitterCard]
    generate = true
    card = "summary"
    image = "images/twitter-card-summary-image.jpg"
    imageAlt = "Dereck Curry's avatar"
    site = "dereckcurry"
    creator = "dereckcurry"
    title = "DereckCurry.com Page"
    description = "A page from DereckCurry.com"
