baseurl = "/"
title = "estebanvalencia.com"
theme = "hugo-theme-console"
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true
  footerText = "*“The soul that is within me no man can degrade.”* – Frederick Douglass"
  summary = "This is a heart warming summary about the joys of reading my content"
  description = "This is a description of the website"
  favicon = "sam.ico"

  [[params.navlinks]]
  name = "me/"
  url = "me/"

  [[params.navlinks]]
  name = "collection/"
  url = "collection/"
  
  [[params.navlinks]]
  name = "photos/"
  url = "photos/"
  
[[params.plugins.css]]
URL = "hugo-theme-console/css/terminal-0.7.1.min.css"
[[params.plugins.css]]
URL = "hugo-theme-console/css/animate-3.7.2.min.css"
[[params.plugins.css]]
URL = "hugo-theme-console/css/console.css"
[[params.plugins.css]]
URL = "css/hugo-easy-gallery.css"
[[params.plugins.css]]
URL = "css/style.css"
[[params.plugins.css]]
URL = "css/fontawesome.min.css" 
