baseurl = "https://estebanvalencia.com"
title = "estebanvalencia.com"

theme = "hugo-theme-console"
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true
  pre = "Esteban | ˈe-stə-vən"
  #footerText = "*“The soul that is within me no man can degrade.”* – Frederick Douglass"
  footerText = "*“The difference between a flower and a weed is judgement.”* – Unknown"
  summary = "Hi visitor!  If you're not quite sure where to start, here's a a heart warming summary about the joys of reading my content"
  description = "Bite-sized ideas sourced from the internet"
  images = "favicon/apple-touch-icon-57x57.png"
  favicon = "sam.ico"
  amp = true
  ampElements = ["amp-accordion","amp-ad","amp-analytics","amp-app-banner","amp-carousel","amp-iframe","amp-dynamic-css-classes","amp-form","amp-fx-flying-carpet","amp-image-lightbox","amp-lightbox","amp-sidebar","amp-social-share","amp-sticky-ad","amp-user-notification"]
  themeColor = "#ff1d55"
  adsensePublisher = "ca-pub-123456789"
  googleAnalytics = "UA-12345678-123"
  appleItunesApp = "app-id=123456789, app-argument=app-name://link/to/app-content"
  ampManifest = "/amp-manifest.json"
  alternatePageName = "HUGO AMP"
  organizationLogo = "https://gohugo-amp.gohugohq.com/logo.png"
  organizationName = "gohugohq.com"
  organizationAddress = "Some Street 123, 12345 City"
  socialProfiles = ["http://www.facebook.com/your-profile","http://instagram.com/yourProfile","http://www.linkedin.com/in/yourprofile","http://plus.google.com/your_profile"]
  publisherName = "gohugohq.com"
  publisherLogo = "https://gohugo-amp.gohugohq.com/logo-publisher.png" # https://developers.google.com/search/docs/data-types/articles#logo-guidelines
  publisherLogoWidth = 600
  publisherLogoHeight = 60
  stylesheetRegular = ["/base-styling.css"] # these styles are used when amp is disabled for a specific page
  javascriptRegular = ["/script.js"] # these scripts are used when amp is disabled for a specific page

  
[[params.navlinks]]
name = "me/"
url = "me/"

[[params.navlinks]]
name = "collection/"
url = "collection/"
  
[[params.navlinks]]
name = "photos/"
url = "photos/"
  
[[params.plugins.css]]
URL = "hugo-theme-console/css/terminal-0.7.1.min.css"
[[params.plugins.css]]
URL = "hugo-theme-console/css/animate-3.7.2.min.css"
[[params.plugins.css]]
URL = "hugo-theme-console/css/console.css"
[[params.plugins.css]]
URL = "css/hugo-easy-gallery.css"
[[params.plugins.css]]
URL = "css/style.css"


[params.twitterCard]
    generate = true
    card = "summary"
    image = "images/twitter-card-summary-image.jpg"
    imageAlt = "Dereck Curry's avatar"
    site = "dereckcurry"
    creator = "dereckcurry"
    title = "DereckCurry.com Page"
    description = "A page from DereckCurry.com"