name: 'Approve DEV pull request'

on:
  push:
    branches:
    - dev
  schedule:
    - cron: "0 * * * *"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1